# Generated by Django 3.2.4 on 2021-07-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
