# Generated by Django 3.2.4 on 2021-07-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0003_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
